spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    database: mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${DATABASE_URI}
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    url: ./swagger.yaml
hateaos:
  user:
    type: GET
    rel: user
    uri: ${HATEAOS_USER_URI}
  team:
    type: GET
    rel: team
    uri: ${HATEAOS_TEAM_URI}